StoryBoard/Controllers/BaseController.cs
using StoryBoard.Security;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace StoryBoard.Controllers
{
    public abstract class BaseController : Controller
    {
        protected StoryBoardIdentity Identity
        {
            get
            {
                return User.Identity as StoryBoardIdentity;
            }
        }
    }
}

StoryBoard/Controllers/GroupsController.cs
using StoryBoard.Business;
using StoryBoard.Model;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace StoryBoard.Controllers
{
    [Authorize]
    public class GroupsController : BaseController
    {
        private readonly GroupLogic _groupLogic;

        public GroupsController(GroupLogic groupLogic)
        {
            _groupLogic = groupLogic;
        }

        public ActionResult Index(int? page)
        {
            var groups = _groupLogic.GetAll(page);
            return View(groups);
        }

        public ActionResult Create()
        {
            var group = new GroupModel();
            return View("Edit", group);
        }

        public ActionResult Edit(int id)
        {
            var group = _groupLogic.Get(id);
            return View(group);
        }

        public ActionResult Details(int id)
        {
            var userId = Identity.UserId;
            var group = _groupLogic.Get(id, userId);
            return View(group);
        }

        public ActionResult DeleteConfirm(int id)
        {
            var group = _groupLogic.Get(id);
            return View(group);
        }

        public async Task<ActionResult> Join(int id)
        {
            var userId = Identity.UserId;
            await _groupLogic.Join(id, userId);
            return RedirectToAction("Details", new { id = id });
        }

        public async Task<ActionResult> Leave(int id)
        {
            var userId = Identity.UserId;
            await _groupLogic.Leave(id, userId);
            return RedirectToAction("Details", new { id = id });
        }

        [HttpPost]
        public async Task<ActionResult> Edit(GroupModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            try
            {
                model.OwnerId = Identity.UserId;
                await _groupLogic.Edit(model);
            }
            catch (ArgumentException ex)
            {
                ModelState.AddModelError(ex.ParamName, ex.Message);
                return View(model);
            }
            catch (Exception)
            {
                throw;
            }

            return RedirectToAction("Index");
        }

        [HttpPost]
        public async Task<ActionResult> Delete(int groupId)
        {
            await _groupLogic.Delete(groupId);
            return RedirectToAction("Index");
        }
    }
}

StoryBoard/Controllers/SecurityController.cs
using StoryBoard.Business;
using StoryBoard.Model;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;

namespace StoryBoard.Controllers
{
    public class SecurityController : BaseController
    {
        private readonly UserLogic _userLogic;

        public SecurityController(UserLogic userLogic)
        {
            _userLogic = userLogic;
        }

        public ActionResult Register()
        {
            return View();
        }

        public ActionResult Login()
        {
            return View();
        }

        public ActionResult LogOut()
        {
            FormsAuthentication.SignOut();
            return RedirectToAction("Login");
        }

        [HttpPost]
        public async Task<ActionResult> Register(UserRegisterModel model)
        {
            if(!ModelState.IsValid)
            {
                return View(model);
            }

            try
            {
                await _userLogic.Register(model);
            }
            catch (ArgumentException ex)
            {
                ModelState.AddModelError(ex.ParamName, ex.Message);
                return View(model);
            }
            catch(Exception)
            {
                throw;
            }

            FormsAuthentication.RedirectFromLoginPage(model.Name, false);

            return View(model);
        }

        [HttpPost]
        public ActionResult Login(UserLoginModel model)
        {
            if(!ModelState.IsValid)
            {
                return View(model);
            }

            try
            {
                _userLogic.Login(model);
            }
            catch (ArgumentException ex)
            {
                ModelState.AddModelError(ex.ParamName, ex.Message);
                return View(model);
            }
            catch (Exception)
            {
                throw;
            }

            FormsAuthentication.RedirectFromLoginPage(model.Name, false);

            return View(model);
        }
    }
}

StoryBoard/Controllers/StoriesController.cs
using StoryBoard.Business;
using StoryBoard.Model;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace StoryBoard.Controllers
{
    [Authorize]
    public class StoriesController : BaseController
    {
        private readonly StoryLogic _storyLogic;
        private readonly GroupLogic _groupLogic;

        public StoriesController(StoryLogic storyLogic, GroupLogic groupLogic)
        {
            _storyLogic = storyLogic;
            _groupLogic = groupLogic;
        }

        public ActionResult Index(int? page)
        {
            var userId = Identity.UserId;
            var stories = _storyLogic.GetUserStories(userId, page);
            return View(stories);
        }

        public ActionResult Create()
        {
            var userId = Identity.UserId;
            ViewBag.GroupOptions = new MultiSelectList(_groupLogic.GetUserGroups(userId), "GroupId", "Name");

            var story = new StoryModel();
            return View("Edit", story);
        }

        public ActionResult Edit(int id)
        {
            var userId = Identity.UserId;
            var story = _storyLogic.Get(id);

            ViewBag.GroupOptions = new MultiSelectList(_groupLogic.GetUserGroups(userId), "GroupId", "Name", story.Groups);

            return View(story);
        }

        public ActionResult Details(int id)
        {
            var story = _storyLogic.Get(id);
            return View(story);
        }

        public ActionResult DeleteConfirm(int id)
        {
            var story = _storyLogic.Get(id);
            return View(story);
        }

        [HttpPost]
        public async Task<ActionResult> Edit(StoryModel model)
        {
            if(!ModelState.IsValid)
            {
                return View(model);
            }

            try
            {
                model.UserId = Identity.UserId;
                await _storyLogic.Edit(model);
            }
            catch (ArgumentException ex)
            {
                ViewBag.GroupOptions = new MultiSelectList(_groupLogic.GetUserGroups(Identity.UserId), "GroupId", "Name", model.Groups);
                ModelState.AddModelError(ex.ParamName, ex.Message);
                return View(model);
            }
            catch (Exception)
            {
                throw;
            }

            return RedirectToAction("Index");
        }

        [HttpPost]
        public async Task<ActionResult> Delete(int storyId)
        {
            await _storyLogic.Delete(storyId);
            return RedirectToAction("Index");
        }
    }
}

StoryBoard/Views/Groups/DeleteConfirm.cshtml
@model StoryBoard.Model.GroupModel

@{
    ViewBag.Title = "DeleteConfirm";
}

<h2>DeleteConfirm</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <hr />
    <dl class="dl-horizontal">

        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

    </dl>

    @using (Html.BeginForm("Delete", "Groups")) {
        @Html.AntiForgeryToken()
        @Html.HiddenFor(m => m.GroupId)
        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

StoryBoard/Views/Groups/Details.cshtml
@model StoryBoard.Model.GroupModel

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

    </dl>
</div>
<p>
    @if(Model.IsSubscribed)
    {
        @Html.ActionLink("Leave Group", "Leave", new { id = Model.GroupId })
    }
    else
    {
        @Html.ActionLink("Join Group", "Join", new { id = Model.GroupId })
    } |
    @Html.ActionLink("Edit", "Edit", new { id = Model.GroupId }) |
    @Html.ActionLink("Back to List", "Index")
</p>

StoryBoard/Views/Groups/Edit.cshtml
@model StoryBoard.Model.GroupModel

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm("Edit", "Groups"))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(m => m.GroupId)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

StoryBoard/Views/Groups/Index.cshtml
@model PagedModel<GroupModel>

@{
    ViewBag.Title = "Groups";
}

<h2>@ViewBag.Title</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            Name
        </th>
        <th>
            Description
        </th>
        <th>
            Members
        </th>
        <th>
            Stories
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model.List)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>
                @item.SubscribersCount
            </td>
            <td>
                @item.StoriesCount
            </td>
            <td>
                @if (item.OwnerId == (User.Identity as StoryBoard.Security.StoryBoardIdentity).UserId)
                {
                    <text>
                        @Html.ActionLink("Edit", "Edit", new { id = item.GroupId }) |
                        @Html.ActionLink("Details", "Details", new { id = item.GroupId })
                        @if (item.StoriesCount == 0 && item.SubscribersCount == 0)
                        {
                            <text>
                                | @Html.ActionLink("Delete", "DeleteConfirm", new { id = item.GroupId })
                            </text>
                        }
                    </text>
                }
            </td>
        </tr>
    }

</table>

<nav>
    <ul class="pagination">
        @if (Model.PageStart > Model.PageLength)
        {
            <li>
                <a href="@Url.Action("Index", new { page = Model.PageStart - Model.PageLength })" aria-label="Previous">
                    <span aria-hidden="true">&laquo;</span>
                </a>
            </li>
        }
        else
        {
            <li class="disabled">
                <a href="#" aria-label="Previous">
                    <span aria-hidden="true">&laquo;</span>
                </a>
            </li>
        }
        @for (int i = Model.PageStart; i <= Model.PageEnd; i++)
        {
            <li><a href="@Url.Action("Index", new { page = i })">@i.ToString()</a></li>
        }
        @if (Model.PageEnd < Model.PageCount)
        {
            <li>
                <a href="@Url.Action("Index", new { page = Model.PageEnd + 1 })" a aria-label="Next">
                    <span aria-hidden="true">&raquo;</span>
                </a>
            </li>
        }
        else
        {
            <li class="disabled">
                <a href="#" aria-label="Next">
                    <span aria-hidden="true">&raquo;</span>
                </a>
            </li>
        }
    </ul>
</nav>

StoryBoard/Views/Security/Login.cshtml
@model StoryBoard.Model.UserLoginModel

@{
    ViewBag.Title = "Login";
}

<h2>Login</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-5">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-5">
                @Html.PasswordFor(model => model.Password, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Login" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Register", "Register")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

StoryBoard/Views/Security/Register.cshtml
@model StoryBoard.Model.UserRegisterModel

@{
    ViewBag.Title = "Register";
}

<h2>Register</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.PasswordFor(model => model.Password, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ConfirmPassword, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.PasswordFor(model => model.ConfirmPassword, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ConfirmPassword, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Register" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Login", "Login")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

StoryBoard/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Story Board</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Story Board", "Index", "Stories", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Groups", "Index", "Groups")</li>
                    <li>@Html.ActionLink("Log Out", "LogOut", "Security")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Story Board</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

StoryBoard/Views/Stories/DeleteConfirm.cshtml
@model StoryModel

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Content)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Content)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PostedOn)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PostedOn)
        </dd>

    </dl>

    @using (Html.BeginForm("Delete", "Stories")) {
        @Html.AntiForgeryToken()
        @Html.HiddenFor(m => m.StoryId)
        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

StoryBoard/Views/Stories/Details.cshtml
@model StoryModel

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <hr />
    <dl class="dl-horizontal">

        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Content)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Content)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PostedOn)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PostedOn)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.StoryId }) |
    @Html.ActionLink("Back to List", "Index")
</p>

StoryBoard/Views/Stories/Edit.cshtml
@model StoryModel

@{
    if(Model.StoryId > 0)
    {
        ViewBag.Title = "Edit";    
    }
    else
    {
        ViewBag.Title = "Create";
    }
}

<h2>@ViewBag.Title</h2>


@using (Html.BeginForm("Edit", "Stories"))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(m => m.StoryId)
        @Html.HiddenFor(m => m.PostedOn)

        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control input-large" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Content, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.Content, new { @class = "form-control", rows = 15 })
                @Html.ValidationMessageFor(model => model.Content, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Groups, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.ListBoxFor(model => model.Groups, ViewBag.GroupOptions as MultiSelectList, new { @class = "form-control", rows = 15 })
                @Html.ValidationMessageFor(model => model.Groups, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

StoryBoard/Views/Stories/Index.cshtml
@{
    ViewBag.Title = "Stories";
}

<h2>Stories</h2>